### ISSUE TITLE
Wallarm removed?

### ISSUE THREAD

**Issue by ragnar1505** [IBM/IBM-QRadar-Universal-Cloud-REST-API#102]
Hey , 
I saw Wallarm connection XMLs here before the update .
can someone share it please? not working anymore ?

BR

**Comment by ChrisCollinsIBM** [comment]
Have a look here:

https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/tree/0e495841a6ede6c602d8a3a082723f94d430f062

That's the state of the repo before I did the folder re-organization. It's certainly possible I might have missed something but I don't see anything for "Wallarm" there.

**Comment by cr-SufDafna** [comment]
Hey , ohh thanks a lot so its my mistake . 

BR

**Comment by ChrisCollinsIBM** [comment]
No problem, just wanted to make sure I didn't miss something in the folder restructuring.
