### ISSUE TITLE
Nozomi Networks Vantage Workflow

### ISSUE THREAD

**Issue by nicoloereni** [IBM/IBM-QRadar-Universal-Cloud-REST-API#105]
Workflow to get the Alerts and Assets data from a Nozomi Networks Vantage instance.
To make it works you must configure the Workflow parameter values with the endpoint of a Vantage instance, the key_name and the key_token generate in that instance and the organization name from which you want to get data.

**Comment by ChrisCollinsIBM** [comment]
Merged
