### ISSUE TITLE
How do we concatenate <>

### ISSUE THREAD

**Issue by Parismtl** [IBM/IBM-QRadar-Universal-Cloud-REST-API#107]
I would like to add special characters like <,>,/,\
Here is an example

<Set path="/logs" value=" <12> ${/logs}" />

Thank you for your help

Best Regards

**Comment by ChrisCollinsIBM** [comment]
Do you have an example of something that isn't working?

**Comment by Parismtl** [comment]
Hi, yes i have

<Set path="/limit" value="<123> ${/limit}" />

Thanks for your help

Best regards

M-A
De : ***@***.*** ***@***.***>
Envoyé : 10 juin 2022 18:54
À : IBM/IBM-QRadar-Universal-Cloud-REST-API ***@***.***>
Cc : PELLETIER Marc Andrew - externe ***@***.***>; Author ***@***.***>
Objet : Re: [IBM/IBM-QRadar-Universal-Cloud-REST-API] How do we concatenate <> (Issue #107)


Do you have an example of something that isn't working?

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIBM%2FIBM-QRadar-Universal-Cloud-REST-API%2Fissues%2F107%23issuecomment-1152555278&data=05%7C01%7Cmarc-andrew-externe.pelletier%40edf.fr%7C424c6613bd064d5e04e908da4b01e1c8%7Ce242425b70fc44dc9ddfc21e304e6c80%7C1%7C0%7C637904768699322800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2N0Vy3MivuYOVfEy%2BHlsdCB3Mtmmk3JyEJJcfE2ZC34%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYQJVBAH5RTTU2BDCF4JV2DVONXL7ANCNFSM5YN7TN3A&data=05%7C01%7Cmarc-andrew-externe.pelletier%40edf.fr%7C424c6613bd064d5e04e908da4b01e1c8%7Ce242425b70fc44dc9ddfc21e304e6c80%7C1%7C0%7C637904768699322800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dMLyR86TmVHpU4kDogBa0uTXdWMT5XYndVjIfQJKQSg%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>



Ce message et toutes les pièces jointes (ci-après le 'Message') sont établis à l'intention exclusive des destinataires et les informations qui y figurent sont strictement confidentielles. Toute utilisation de ce Message non conforme à sa destination, toute diffusion ou toute publication totale ou partielle, est interdite sauf autorisation expresse.

Si vous n'êtes pas le destinataire de ce Message, il vous est interdit de le copier, de le faire suivre, de le divulguer ou d'en utiliser tout ou partie. Si vous avez reçu ce Message par erreur, merci de le supprimer de votre système, ainsi que toutes ses copies, et de n'en garder aucune trace sur quelque support que ce soit. Nous vous remercions également d'en avertir immédiatement l'expéditeur par retour du message.

Il est impossible de garantir que les communications par messagerie électronique arrivent en temps utile, sont sécurisées ou dénuées de toute erreur ou virus.
____________________________________________________

This message and any attachments (the 'Message') are intended solely for the addressees. The information contained in this Message is confidential. Any use of information contained in this Message not in accord with its purpose, any dissemination or disclosure, either whole or partial, is prohibited except formal approval.

If you are not the addressee, you may not copy, forward, disclose or use any part of it. If you have received this message in error, please delete it and all copies from your system and notify the sender immediately by return message.

E-mail communication cannot be guaranteed to be timely secure, error or virus-free.
