### ISSUE TITLE
SSLHandshakeTest 

### ISSUE THREAD

**Issue by dicolanl** [IBM/IBM-QRadar-Universal-Cloud-REST-API#117]
I am working on a new workflow here https://github.com/dicolanl/IBM-QRadar-Universal-Cloud-REST-API/tree/ZeroNetworksV1/Community%20Developed/ZeroNetworks

I had to comment out <SSLHandshakeTest host="${/host}" /> as it fails during testing.

using test-workflow.sh -u passes fine.  if i set to allow untrusted certs in the gui config test pass still fails.

same error as #96 

Certificate path:
![image](https://user-images.githubusercontent.com/25964057/178352472-fd964132-8769-4bb5-806c-d601234906f3.png)

**Comment by sarbqdev** [comment]
We face with the same issue, can anyone help with that?

**Comment by ChrisCollinsIBM** [comment]
> I am working on a new workflow here https://github.com/dicolanl/IBM-QRadar-Universal-Cloud-REST-API/tree/ZeroNetworksV1/Community%20Developed/ZeroNetworks
> 
> I had to comment out as it fails during testing.
> 
> using test-workflow.sh -u passes fine. if i set to allow untrusted certs in the gui config test pass still fails.
> 
> same error as #96
> 
> Certificate path: ![image](https://user-images.githubusercontent.com/25964057/178352472-fd964132-8769-4bb5-806c-d601234906f3.png)

In your example above `Sectigo RSA Domain Validation Secure Server CA` from what I can see is not a Root CA that is in the Linux default Root CA bundle and likely isn't on whatever machine you're using, you would need to download and add it to the host doing the call.

**Comment by ChrisCollinsIBM** [comment]
> We face with the same issue, can anyone help with that?

Your issue may be the same symptom but a different cause.

Can you provide the hostname that you're trying to connect to? (if internet facing)

If not can you provide the certificate chain for what you're trying to connect to? Typically it fails because of lack of required certs on the box doing the connecting for certificates that aren't in the main root CA bundles on most OS.

**Comment by dicolanl** [comment]
@ChrisCollinsIBM 
portal.zeronetworks.com is the host for the api.
Chrome shows the intermediate and root ca.
![image](https://user-images.githubusercontent.com/25964057/196221911-0ca3bb63-e7a4-48f6-ab3b-3f1ab57d0b08.png)

**Comment by ChrisCollinsIBM** [comment]
I see that it works with a browser, but browsers can do some funny things.

At a high level you should only trust Root CA and not Intermediates. In the case of portal.zeronetworks.com it is only presenting the subject certificate (issued to `CN=*.zeronetworks.com`) and saying it is issued by `C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA`

`CN=Sectigo RSA Domain Validation Secure Server CA` should then be presented in the chain which is issued by `USERTrust RSA Certification Authority` and is a trusted Root CA and doesn't need to be presented in the chain.

```
openssl s_client -servername portal.zeronetworks.com -connect portal.zeronetworks.com:443 -showcerts
CONNECTED(00000005)
depth=0 CN = *.zeronetworks.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.zeronetworks.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=*.zeronetworks.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA
-----BEGIN CERTIFICATE-----
MIIGQTCCBSmgAwIBAgIQYj1RBFajHHFkYHPJglFCyjANBgkqhkiG9w0BAQsFADCB
jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
MB4XDTIxMTAwMzAwMDAwMFoXDTIyMTEwMTIzNTk1OVowHTEbMBkGA1UEAwwSKi56
ZXJvbmV0d29ya3MuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
paCT9v2ZZzpl2DbMIwLptxMOtLrF/27fs+YHLa7ZCk7Klvce4M+HvMSiIw/mVmgC
8MEfU9XAfwylPOjBxW8Oi/FuToPc9aTHAzq0oFiA3ygAWKprvGqX4siKGMr1rkGg
eKRCLrjLI4Lt3byDOljLe3ZtE7yF9E+A3g9dCXGS2qC1lZKOQCrsaHcnA5J9+Hvf
D30brWlMaNjSc8vlLpI0g1eaYY3HHHR0Sg8WQvmCBQBIiwUt856VNdFHyNIWbj8z
Clz/fsms/j8Q2UP1hXbgXWlNtPN8R/OYBpdj9ltj6x99kBBg11ASxpbkeGt2LxP0
PcaleFfptmfKUiVMnTC33QIDAQABo4IDCDCCAwQwHwYDVR0jBBgwFoAUjYxexFSt
iuF36Zv5mwXhuAGNYeEwHQYDVR0OBBYEFGV9f7Waf1KgSjdtyRPBYfB5k60iMA4G
A1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMB
BggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysGAQQBsjEBAgIHMCUwIwYIKwYBBQUH
AgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BTMAgGBmeBDAECATCBhAYIKwYBBQUH
AQEEeDB2ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LnNlY3RpZ28uY29tL1NlY3Rp
Z29SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCMGCCsGAQUF
BzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTAvBgNVHREEKDAmghIqLnplcm9u
ZXR3b3Jrcy5jb22CEHplcm9uZXR3b3Jrcy5jb20wggGABgorBgEEAdZ5AgQCBIIB
cASCAWwBagB2AEalVet1+pEgMLWiiWn0830RLEF0vv1JuIWr8vxw/m1HAAABfEU/
cSsAAAQDAEcwRQIhAI/Oyfzm/LgdpLB/IR9YGYDVFz0bHU18zYlJjxuNVQ8zAiBC
BMKpl0UM7H078Hs6JjQ0vgpW+bEMP/2edYce8n0jNQB3AEHIyrHfIkZKEMahOglC
h15OMYsbA+vrS8do8JBilgb2AAABfEU/cOsAAAQDAEgwRgIhAPV8PSLmLgtHcy97
1bRpHUAXgIJl/Q5ljurmPhEh5pb3AiEA5D7NKvPP9d5TAk5eQJA3a5qGiROURnZS
JVIEjrMHeXcAdwApeb7wnjk5IfBWc59jpXflvld9nGAK+PlNXSZcJV3HhAAAAXxF
P3DIAAAEAwBIMEYCIQD+IUsL3uMYo05w1ncXFRXionD2ruK+34iDpD7/u5c79wIh
AIvqjOfAd6NX0dZXlxziCQBMgTyT0iKsRVMaXl3Aed6rMA0GCSqGSIb3DQEBCwUA
A4IBAQB389xYtISB4WaGSPt0yniZLaxrimy3ddDjQsGlglTMEQEcT5xtQzCmKJ6J
mDh9PA5yxVIPKEQVOekEpJM1ptHyIMiQugUxY0c+I1pTJ5OFdfZxCVEzjLDAilU3
rE0nTvkkiEgDrqZatUlIpbnEBIhy62PmtRN687VhMU2pYMR2Znvd5BrFKy75JlH3
DdpsueJYZbQmqE5J3jJL/7v/9dAEK7jJgybd44rbsNT2tuvoxZhgWfj2ypXrBg1C
YKxw+PJL/vyxvnSVUmuMReTdA9s4pTb1BzFUILCmpo6YB4uAJM1bFAR7D7ijxFDW
V/eUuFjLuxzmOgDnUiMzrPEtKVr8
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=*.zeronetworks.com
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 2248 bytes and written 313 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
    Session-ID: F9424D626CAC114561266ADCC8EE908B8346223B9AEF8D398C7B64CB96A1848C
    Session-ID-ctx:
    Master-Key: 83A02D60BAFBE3F28A8EC8E48D76C5538C108FCBCABD5DCE3D2E82916DEA84AB814D5C7756F4280F2B641685B23E7D5B
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - e6 5c cb a8 47 97 bd ae-8a 8f 9d 23 d7 99 bd 4b   .\..G......#...K
    0010 - 32 02 e3 7e 78 32 1a 2c-54 33 f4 0d 37 b9 e5 b0   2..~x2.,T3..7...
    0020 - 4a 92 61 f0 79 44 30 0c-4c e7 a0 4d 73 00 f6 01   J.a.yD0.L..Ms...
    0030 - 3c 6f 51 a5 e3 09 db 5d-01 f6 5b 98 63 95 38 61   <oQ....]..[.c.8a
    0040 - dc ef 36 70 ab c8 a9 cb-13 04 29 c6 36 49 90 fe   ..6p......).6I..
    0050 - 1b 84 95 8c b5 2f 19 3c-e4 d5 8c cf 14 38 d5 8e   ...../.<.....8..
    0060 - fb b9 79 bc a1 14 48 31-35 9d 8b 50 2e 5a 84 39   ..y...H15..P.Z.9
    0070 - 9d 18 da 1e a8 e8 35 87-4a f8 86 90 ed bd 34 90   ......5.J.....4.
    0080 - 34 17 b7 23 ed 40 42 94-0b de e7 e5 51 91 51 7b   4..#.@B.....Q.Q{
    0090 - d4 43 18 2f b2 e8 2f 5e-39 5c 95 31 5e df 24 8b   .C./../^9\.1^.$.
    00a0 - 58 ef 85 b3 ce ec e4 5c-f6 4b 0f ae 64 93 08 18   X......\.K..d...
    00b0 - e3 b6 53 fa 30 a6 91 dc-cc 15 fb dd 68 11 9e ef   ..S.0.......h...

    Start Time: 1666729179
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

So you -can- add the `Sectigo RSA Domain Validation Secure Server CA` certificate to the QRadar trusted anchors, but it's generally not a good idea to add intermediates.

But in my opinion that's why the SSL Handshake is failing, that output above with OpenSSL failing to validate the chain provided is from my Mac, not a QRadar machine and I get the same result from an AWS Linux install and a QRadar RedHat install.
