### ISSUE TITLE
Cookie Session Issue

### ISSUE THREAD

**Issue by Parismtl** [IBM/IBM-QRadar-Universal-Cloud-REST-API#130]
Hello I have to make the recovery of the XSRF-TOKEN in a cokie, but when I make my request, I miss information, I looked on the Issue, you had given a link with examples, but this link does not work anymore. It was with OKTA I think. 
I thank you for your help. 

Best regard, 

M-A

**Comment by vvilaine** [comment]
@Parismtl OKTA workflow script is here https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/blob/f0fa7a3019e18ece3e0e339638ba11bbce1c6d4e/IBM%20Proof%20Of%20Concept/Okta/Okta-Workflow.xml

**Comment by Parismtl** [comment]
Hi, after checking with the manufacturer, there are 5 cookies that are transmitted during the identification process. The token I need is in a cookie. 
It is not possible to make a request and retrieve this cookie?
Will API Universal be able to do this soon?
This is very urgent for us.
Thank you very mush

Best regards

![Oodrive](https://user-images.githubusercontent.com/102800004/196363889-8b8ece00-8176-4c6c-b8d4-04c6d61a04ca.jpg)

**Comment by ChrisCollinsIBM** [comment]
Cooke support for both extracting cookies from the response AND attaching your own to the request will be in the next release of the Universal Cloud RESTAPI Protocol RPM.

Cookies will be stored in the <CallEndpoint> response and can be attached with a new <RequestCookie> tag. Details will be in the updated documentation when released.

**Comment by ChrisCollinsIBM** [comment]
Cookie support has been release in `PROTOCOL-UniversalCloudRESTAPI-7.5-20240812075740.noarch.rpm` and I've posted details here: #263
