### ISSUE TITLE
how to integrate webhook based (auth0) in qradar?

### ISSUE THREAD

**Issue by manimmt** [IBM/IBM-QRadar-Universal-Cloud-REST-API#234]
how to integrate webhook based (auth0) in qradar? guide if that is possible using http receiver

**Comment by ChrisCollinsIBM** [comment]
HTTP receiver can accept post data from just about anything. If the entire POST data is a single message then it can be multiline and use a blank message pattern, if multiple messages are in the same POST they must be one per line and in the log source configuration use a message pattern of `.*` 

```
Message Pattern (Optional)
By default, the entire HTTP Post is processed as a single event. To split that post into multiple single-line events, provide a regular expression to denote the start of each event.
```

This is not Universal REST related however, so closing this issue.
