### ISSUE TITLE
Add a workflow for XPANSE.

### ISSUE THREAD

**Issue by rislas83** [IBM/IBM-QRadar-Universal-Cloud-REST-API#236]
Workflows required for the QRadar XPANSE extension.

**Comment by ChrisCollinsIBM** [comment]
Hello @rislas83, it appears that you have multiple pull requests open (one for each file).

Can you please unify what you would like merged into a single pull request?

Thanks!

**Comment by ChrisCollinsIBM** [comment]
Hello @rislas83, still waiting for the multiple pull requests to be combined into a single one so we can review the PR and get you any feedback needed and subsequently get it merged.

**Comment by rislas83** [comment]
@ChrisCollinsIBM I just combined all files into https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/pull/238
