### ISSUE TITLE
Virtru Create JWTAccessToken action output with quotation mark

### ISSUE THREAD

**Issue by MohInteg** [IBM/IBM-QRadar-Universal-Cloud-REST-API#61]
Hello All, 

Can someone help. We try to collect events Cloud using Protocol universal REST API

I have a JWT to be generated using payload parameters : sub, iat , rsha , rqps and exp.
iat represent The current timestamp (seconds)
when we generate the JWT Token with these inputs payload using the action "Create JWTAccessToken"  Example :

<CreateJWTAccessToken savePath="/jwt_assertion">
            <Header>
                <Value name="typ" value="JWT" />
                <Value name="alg" value="HS256" />            
            </Header>       
            <Payload>
                <Value name="sub" value="${/API_ID}" />
		<Value name="iat" value="${time() / 1000}" />
                <Value name="jti" value="20720777" />
                <Value name="rsha" value="xxxxx_xxxxxxxRnvzszxxxx_9xxx" />
                <Value name="rqps" value="start,end" />               
		<Value name="exp" value="${time() / 1000 + 100}" />
            </Payload>
            
            <Secret value="${/API_Secret}" />
        </CreateJWTAccessToken>

I have a Wrong JWT token compared with the token that might be generated because the "iat" is represented with quotes "" and not as a date like exp. 

Wrong token example : eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Mjk5ODM0NzksImp0aSI6IjIwNzIwNzc3IiwicnFwcyI6InN0YXJ0LGVuZCIsImlhdCI6IjE2Mjg1OTgzNzIiLCJyc2hhIjoieHh4eHh4eF94eHh4eHh4eHpzelZEXzkwTSIsInN1YiI6IjEweHh4eHgxLXh4eHh4LTI0MjMtYTU0Wi14eHh4eHhkZkB0b2tlbnMueHh4eHgifQ.TSlSfEC7vYc5avlfia-WcLgQ79q9qMc7_ocEvzeJivY
Correct token example : 
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Mjk5ODM0NzksImp0aSI6IjIwNzIwNzc3IiwicnFwcyI6InN0YXJ0LGVuZCIsImlhdCI6MTYyODU5ODM3MiwicnNoYSI6Inh4eHh4eHhfeHh4eHh4eHh6c3pWRF85ME0iLCJzdWIiOiIxMHh4eHh4MS14eHh4eC0yNDIzLWE1NFoteHh4eHh4ZGZAdG9rZW5zLnh4eHh4In0.7xvbhpE_wCTQ-uR1yvFWQ9bueJMXUIOFRPd6xoXaE4M

This is the resulat Payload that I might have when typing this TokenJWT on https://jwt.io/
{
  "exp": 1629983479,
  "jti": "20720777",
  "rqps": "start,end",
  "iat": "1628598372",
  "rsha": "xxxxxxx_xxxxxxxxzszVD_90M",
  "sub": "10xxxxx1-xxxxx-2423-a54Z-xxxxxxdf@tokens.xxxxx"
}

and This is the result that I should have : ( iat without mark quotation mark ""  )
{
  "exp": 1629983479,
  "jti": "20720777",
  "rqps": "start,end",
  "iat": 1628598372,
  "rsha": "xxxxxxx_xxxxxxxxzszVD_90M",
  "sub": "10xxxxx1-xxxxx-2423-a54Z-xxxxxxdf@tokens.xxxxx"
}

Do you have an idea how to fix this ?

**Comment by ChrisCollinsIBM** [comment]
This looks to be a bug in the JSON serialization on the QRadar side. I see some handling in the code for the `exp` tag to work around it but nothing for `iat` (or `nbf` which could also show up).

It's probably dependent on the API that you're talking to whether it's more strict in it's JSON handling or not, to be proper numbers are not quoted and strings are so whether some API will accept this or not it's definitely wrong as we're sending it for `iat`.

I've logged issue PROT-1300 internally to address it.

**Comment by MohInteg** [comment]
Hello , 

Do you have any idea @ChrisCollinsIBM how to workaround this ? 

@Fa6s thnak yu for your help ,  I have already tested to use regular expression fucntion but can't resolve using this.

**Comment by ChrisCollinsIBM** [comment]
> Hello ,
> 
> Do you have any idea @ChrisCollinsIBM how to workaround this ?
> 
> @Fa6s thnak yu for your help , I have already tested to use regular expression fucntion but can't resolve using this.

No ETA yet, but this is the type of issue you can open up a case with IBM Support for as it's an issue with the Universal REST RPM for QRadar and not a workflow problem. If you reference the PROT-1300 I mentioned we can get your case # attached to the workitem.

Thanks!

**Comment by MohInteg** [comment]
Yes, I have already try to run the workflow without this value but it's it's work. 

I had already created a ticket IBM to see this issue.

**Comment by ChrisCollinsIBM** [comment]
This is still an open issue with QRadar development, and when we have some updates on the status we will definitely update it here. Thanks.

**Comment by ChrisCollinsIBM** [comment]
This is still an open issue, but is nearly completed development, stay tuned!
