### ISSUE TITLE
Orca Security Workflow Error

### ISSUE THREAD

**Issue by maximpoleley** [IBM/IBM-QRadar-Universal-Cloud-REST-API#88]
Periodically we seeing this error: 
> get_alerts/body/next_page_token is not valid

We believe that is because our api not always returns the **next_page_token** field.

Is there a way to check if **next_page_token** exists in a response?

Code:
https://github.com/ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API/blob/master/Orca%20Security/Orca-Security-Workflow.xml#L23

Thanks.

**Comment by ChrisCollinsIBM** [comment]
I believe this has been resolved by @yuri-orca in #90 - can you confirm?
