### ISSUE TITLE
Workflow - Troubleshooting Logs

### ISSUE THREAD

**Issue by MikeNguyen-ISA** [IBM/IBM-QRadar-Universal-Cloud-REST-API#93]
Hi,

While looking at the code used to collect Cisco DUO, I wanted to pull a similar log from Cisco as well but cannot seem to find out where to find errors when running the code.

The API is for AMP Audit logs which are not collected because it is not supported by the event_stream which is pulled by the RabbitMSQ

https://api-docs.amp.cisco.com/api_actions/details?api_action=GET+%2Fv1%2Faudit_logs&api_host=api.amp.cisco.com&api_resource=AuditLog&api_version=v1

**Comment by ChrisCollinsIBM** [comment]
If you're trying to get the data from Cisco AMP, that's via AMQP and not a REST API. There is a RESTAPI available to manage the streams but not to consume the data itself. 

https://www.ibm.com/docs/en/dsm?topic=cisco-amp
